# Generated by Django 5.0.6 on 2024-06-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('finance', 'Finance Consultant'), ('business', 'Business Consultant'), ('advice', 'Financial Advices'), ('growth', 'Business Growth')], max_length=200)),
                ('message', models.TextField()),
                ('subscribe', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
