# Generated by Django 5.0.6 on 2024-07-09 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_appointment_created_at_email_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='created_at',
        ),
    ]
