# Generated by Django 5.0.6 on 2024-07-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_appointment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='subject',
            field=models.CharField(choices=[('finance', 'Finance Consultant'), ('business', 'Business Consultant'), ('advice', 'Financial Advices'), ('growth', 'Business Growth')], max_length=200),
        ),
    ]
