# Generated by Django 5.0.6 on 2024-07-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_appointment_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
